# frozen_string_literal: true

require "bundler/setup"
require "dotenv/load"
require "semantic_logger"

# Configure structured logging before anything else
SemanticLogger.default_level = ENV.fetch("LOG_LEVEL", "info").to_sym
SemanticLogger.add_appender(io: $stderr, formatter: :json)

require_relative "../lib/homunculus/version"
require_relative "../lib/homunculus/config"
require_relative "../lib/homunculus/utils/logging"
require_relative "../lib/homunculus/session"
require_relative "../lib/homunculus/security/audit"
require_relative "../lib/homunculus/security/sandbox"
require_relative "../lib/homunculus/security/content_sanitizer"
require_relative "../lib/homunculus/security/threat_patterns"
require_relative "../lib/homunculus/security/skill_validator"
require_relative "../lib/homunculus/tools/base"
require_relative "../lib/homunculus/tools/registry"
require_relative "../lib/homunculus/tools/echo"
require_relative "../lib/homunculus/tools/datetime_now"
require_relative "../lib/homunculus/tools/workspace_read"
require_relative "../lib/homunculus/tools/workspace_write"
require_relative "../lib/homunculus/tools/workspace_delete"
require_relative "../lib/homunculus/tools/workspace_list"
require_relative "../lib/homunculus/tools/memory_search"
require_relative "../lib/homunculus/tools/memory_save"
require_relative "../lib/homunculus/tools/memory_daily_log"
require_relative "../lib/homunculus/tools/memory_curate"
require_relative "../lib/homunculus/tools/files"
require_relative "../lib/homunculus/tools/shell"
require_relative "../lib/homunculus/tools/web_session_store"
require_relative "../lib/homunculus/tools/web"
require_relative "../lib/homunculus/tools/web_extract"
require_relative "../lib/homunculus/tools/mqtt"
require_relative "../lib/homunculus/tools/scheduler"
require_relative "../lib/homunculus/memory/indexer"
require_relative "../lib/homunculus/memory/embedder"
require_relative "../lib/homunculus/memory/store"
require_relative "../lib/homunculus/agent/context/token_counter"
require_relative "../lib/homunculus/agent/context/budget"
require_relative "../lib/homunculus/agent/context/compressor"
require_relative "../lib/homunculus/agent/context/window"
require_relative "../lib/homunculus/agent/models"
require_relative "../lib/homunculus/agent/prompt"
require_relative "../lib/homunculus/agent/budget"
require_relative "../lib/homunculus/agent/router"
require_relative "../lib/homunculus/agent/loop"
require_relative "../lib/homunculus/agent/agent_definition"
require_relative "../lib/homunculus/agent/agent_worker"
require_relative "../lib/homunculus/agent/multi_agent_manager"
require_relative "../lib/homunculus/skills/skill"
require_relative "../lib/homunculus/skills/loader"
require_relative "../lib/homunculus/scheduler/job_store"
require_relative "../lib/homunculus/scheduler/notification"
require_relative "../lib/homunculus/scheduler/manager"
require_relative "../lib/homunculus/scheduler/heartbeat"
require_relative "../lib/homunculus/gateway/server"
require_relative "../lib/homunculus/interfaces/cli"
require_relative "../lib/homunculus/interfaces/telegram"
require_relative "../lib/homunculus/interfaces/tui"
